# Generated by Django 3.0 on 2020-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('advisor', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('group', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=40)),
            ],
        ),
    ]
