# Generated by Django 3.0 on 2020-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
