# Generated by Django 3.0 on 2020-06-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_auto_20200626_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('group', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MeetTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('group', models.IntegerField(default=0)),
            ],
        ),
    ]
