# Generated by Django 3.0 on 2020-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereply',
            name='year',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
