# Generated by Django 3.0 on 2020-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200625_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usergrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='userline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='userphone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
