# Generated by Django 3.0 on 2020-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200625_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contactMail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
