# Generated by Django 3.0 on 2020-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_contactmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
