# Generated by Django 3.0.6 on 2020-06-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Please enter your project name', max_length=50)),
                ('person_in_charge', models.CharField(help_text='Please enter your username', max_length=50)),
                ('project_date', models.DateTimeField(auto_now=True, verbose_name='最後修改日期')),
            ],
        ),
    ]
