# Generated by Django 3.0.6 on 2020-06-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate_projects', '0002_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
