# Generated by Django 3.0.6 on 2020-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate_projects', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advisor',
            field=models.CharField(default='teacher', help_text='Please enter your instructor', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
