# Generated by Django 3.0 on 2020-06-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate_projects', '0003_auto_20200616_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Progress_rate',
            field=models.IntegerField(default=0, help_text='Please enter your progress rate'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='private_pj_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='private_text_motive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='private_text_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='text_SystemRequirement',
            field=models.CharField(default='text', help_text='Please enter your group system request', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='text_motive',
            field=models.CharField(default='text', help_text='Please enter your group members username', max_length=1000),
        ),
    ]
