# Generated by Django 3.0 on 2020-06-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate_projects', '0004_auto_20200628_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
